# FarmerPlots Configuration

database:
  file: plugins/FarmerPlots/plots.db

worlds:
  main: plots_main
  tier3: plots_t3
  tier4: plots_t4
  tier5: plots_t5

plot-sizes:
  main: 48
  tier3: 60
  tier4: 70
  tier5: 80

road-width: 4

grid-sizes:
  main: -1  # infinite
  tier3: 30  # 5x6
  tier4: 30
  tier5: 30

warmup-seconds: 3
purge-days: 14
vault-expiry-hours: 24
purge-check-interval-hours: 12
